name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: determinatesystems/nix-installer-action@main
    - run: nix flake check
    - run: nix build .#nixosConfigurations.default.config.system.build.toplevel