name: Neovim

on:
  push:
    branches: [main]
    paths:
      - 'dotfiles/nvim/**'
      - '.github/workflows/neovim.yml'
  pull_request:
    branches: [main]
    paths:
      - 'dotfiles/nvim/**'
      - '.github/workflows/neovim.yml'
  workflow_dispatch:

jobs:
  test:
    name: Neovim (${{ matrix.nvim-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-version:
          - stable
          - nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Show Neovim version
        run: nvim --version

      - name: Test config loads without errors
        run: |
          cd dotfiles/nvim
          nvim --headless -u tests/minimal_init.lua +qa
